basePath: /ingest_v1
host: api.kessler.xyz
info:
  contact:
    email: support@kessler.xyz
    name: Support
    url: https://kessler.xyz
  description: Bob loblaws law blog
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kessler Ingest API
  version: "1.0"
paths: {}
swagger: "2.0"
