# A docker compose for editing the postgres directly
services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    # expose:
    #  - "5432"
    environment:
      POSTGRES_PASSWORD: password

    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
