version: "3"
#

services:
  reverse-proxy:
    # official image
    image: traefik:v2.11

    # eable web ui, listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # rabbitmq:
  #   image: rabbitmq:latest
  #   ports:
  #     - "5672:5672"
  #   volumes:
  #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./volumes/instance:/app/instance
      - ./volumes/files:/files
      - ./volumes/tmp:/tmp/
      - ./server.htpasswd:/app/server.htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${BACKEND_PORT}"
      - "--workers"
      - "4"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./ProdDockerfile
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env.local:/app/.env.local

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

    command:
      - "npm"
      - "run"
      - "start"
      - "--"
      - "-p"
      - "${FRONTEND_PORT}"
