# local development docker compose
services:
  frontend:
    hostname: "app.kessler.xyz"
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    env_file:
      - config/global.env
    volumes:
      - ./config/frontend.env.local:/app/.env.local
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    expose:
      - 3000
    command:
      - "npm"
      - "run"
      - "dev"
      #      - "--"
      #      - "--hostname"
      #      - "${domain:-127.0.0.1}"

  reverse-proxy:
    # official image
    image: traefik:v2.11
    # eable web ui, listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "${PROXY_UI_PORT:-8083}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - config/global.env
    environment:
      - LANCEDB_CONFIG_DIR=/lancedb
    volumes:
      - ./backend:/app
      - ${VOLUMES_DIRECTORY:-./volumes}/instance:/app/instance
      - ${VOLUMES_DIRECTORY:-./volumes}/files:/files
      - ${VOLUMES_DIRECTORY:-./volumes}/tmp:/tmp/
      - ${VOLUMES_DIRECTORY:-./volumes}/lancedb:/lancedb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`) || PathPrefix(`/schema/`)"
    command:
      # - "python"
      # - "rag/postgres_example.py"
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5505"
      - "--workers"
      - "4"
      - "--reload"
    expose:
      - 5505

  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "6543:5432"
    env_file:
      - config/global.env
    expose:
      - "5432"
    volumes:
      - ${VOLUMES_DIRECTORY:-./volumes}/pgdata:/var/lib/postgresql/data
