# local development docker compose
services:
  frontend:
    hostname: kessler.xyz
    image: fractalhuman1/kessler-frontend:latest
    env_file:
      - config/global.env
    volumes:
      - ./config/frontend.env.local:/app.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-kessler.xyz}`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN:-kessler.xyz}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    expose:
      - 3000
    command:
      # - "sleep"
      # - "9999999999d"
      - "npm"
      - "run"
      - "start"

  reverse-proxy:
    # official image
    image: traefik:v3.0
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=mbright@kessler.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "${PROXY_UI_PORT:-8083}:8080"
    volumes:
      - "${VOLUMES_DIRECTORY:-./volumes}/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend-python:
    image: fractalhuman1/kessler-backend-python:latest
    env_file:
      - config/global.env
    volumes:
      - ${VOLUMES_DIRECTORY:-./volumes}/files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-python.rule=Host(`${DOMAIN:-kessler.xyz}`) && PathPrefix(`/api/v1`) || PathPrefix(`/schema`)"
      - "traefik.http.routers.backend-python.entrypoints=websecure"
      - "traefik.http.routers.backend-python.tls.certresolver=myresolver"
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5505"
      - "--workers"
      - "4"
      - "--reload"
    expose:
      - 5505
  backend-go:
    image: fractalhuman1/kessler-backend-go:latest
    command:
      - "go"
      - "run"
      - "main.go"
    env_file:
      - config/global.env
    expose:
      - 4041
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-go.rule=Host(`${DOMAIN:-kessler.xyz}`) && PathPrefix(`/api/v2`)"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/api/v2"
      - "traefik.http.routers.backend-go.entrypoints=websecure"
      - "traefik.http.routers.backend-go.tls.certresolver=myresolver"
