# local development docker compose
x-common-env: &common-env
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
  VERSION_HASH: dev
  DOMAIN: "localhost"
  PUBLIC_KESSLER_API_URL: "http://localhost"
  INTERNAL_KESSLER_API_URL: "http://backend-go:4041"
  INTERNAL_REDIS_ADDRESS: "valkey:6379"
services:
  reverse-proxy:
    image: traefik:v3.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.constraints=Label(`traefik.namespace`,`kessler`)"
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "${PROXY_UI_PORT:-8083}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    hostname: "kessler.xyz"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-dev
    environment:
      <<: *common-env
    env_file:
      - config/global.env
    volumes:
      - ./frontend/src/:/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    expose:
      - 3000
    command:
      - "npm"
      - "run"
      - "dev"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.server.dev
    env_file:
      - config/global.env
    environment:
      <<: *common-env
      air_wd: "/app"
    volumes:
      - ./backend:/app
    working_dir: /app
    expose:
      - 4041
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.go-backend.rule=PathPrefix(`/v2`)"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/v2"

  cache:
    image: memcached:1.6.37-alpine
    command:
      --conn-limit=1024
      --memory-limit=64
      --threads=2
    restart: always
    ports:
      - "11211:12111"

  ingest:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.ingest.dev
    env_file:
      - config/global.env
    environment:
      <<: *common-env
      air_wd: "/app"
    volumes:
      - ./ingest:/app
    working_dir: /app
    expose:
      - 4042
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.ingest.rule=PathPrefix(`/ingest_v1`)"
  valkey:
    hostname: valkey
    image: valkey/valkey:7.2.5
    volumes:
      - ./volumes/valkey.conf:/etc/valkey/valkey.conf
      - ./volumes/valkey-data:/data
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    expose:
      - 6379
  # vector:
  #   image: timberio/vector:latest-alpine
  #   volumes:
  #     - ./vector.yaml:/etc/vector/vector.yaml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --config /etc/vector/vector.yaml
  #   restart: unless-stopped
