# local development docker compose
version: "3"

services:
  reverse-proxy:
    # official image
    image: traefik:v2.11

    # eable web ui, listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  # chroma is handled in process in the backend
  backend:
    build:
      context: ./backend
      # dockerfile: ./Dockerfile
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./volumes/instance:/app/instance
      - ./volumes/files:/files
      - ./volumes/tmp:/tmp/
      - ./server.htpasswd:/app/server.htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
    command:
      # - "python"
      # - "rag/postgres_example.py"
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${BACKEND_PORT}"
      - "--workers"
      - "4"
      - "--reload"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env.local:/app/.env.local

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

    command:
      - "npm"
      - "run"
      - "dev"
      - "--"
      - "-p"
      - "$FRONTEND_PORT"
  database:
    image: pgvector/pgvector:pg16
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password

    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
