# local development docker compose
services:
  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - config/global.env
    expose:
      - "5432"
    volumes:
      - ${VOLUMES_DIRECTORY:-./volumes}/pgdata:/var/lib/postgresql/data
