# local development docker compose
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    env_file:
      - config/global.env
    volumes:
      - ./config/frontend.env.local:/app.env.local
      # - ./frontend/src:/app/src
      # - ./frontend/public:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.tls={}"
    expose:
      - "3000"
    command:
      - "npm"
      - "run"
      - "start"

  reverse-proxy:
    # official image
    image: traefik:v3.0
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=mbright@kessler.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8083:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app.kessler.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  backend:
    build:
      context: ./backend
      # dockerfile: ./Dockerfile
      dockerfile: ./Dockerfile
    env_file:
      - config/global.env
    volumes:
      - ./volumes/instance:/app/instance
      - ./volumes/files:/files
      - ./volumes/tmp:/tmp/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`) && PathPrefix(`/schema`)"
      - "traefik.http.routers.backend.tls={}"
      # - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*"
    command:
      # - "python"
      # - "rag/postgres_example.py"
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5505"
      - "--workers"
      - "4"
      - "--reload"
    expose:
      - 5505
    ports:
      - "5505:5505"

  database:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "6543:5432"
    env_file:
      - config/global.env
    expose:
      - "5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
