filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

output.elasticsearch:
  hosts: ["<quickwit_url>:9200"] # Quickwit's Elasticsearch-compatible endpoint
  indices:
    - index: "kessler-logs-%{+yyyy.MM.dd}"
