## Dynamic configuration
http:
  routers:
    local-frontend-route:
      rule: "Host(`localhost`)) && Path(`/`)"
      service: "frontend"

    local-backend-route:
      rule: " Host(`localhost`) && (PathPrefix(`/api/`) || PathPrefix(`/schema/`))"
      service: "backend"

    prod-frontend-route:
      rule: "Host(`app.kessler.xy`)  && Path(`/`)"
      service: "frontend-1"
      # will terminate the TLS request
      tls: {}
    prod-backend-route:
      rule: "Host(`app.kessler.xy`) && (PathPrefix(`/api/`) || PathPrefix(`/schema/`))"
      service: "backend-1"
      # will terminate the TLS request
      tls: {}
