[sources.docker_logs]
  type = "file"
  path = "/var/lib/docker/containers/*/*-json.log"
  format = "json"
  # Include more configurations as needed

[generators ]
  # Add any generators if needed

[sinks.otlp_sink]
  type = "opentelemetry"
  endpoint = "
		protocol:
			type: http
			uri: "http://logging-nixos-docker.tail4a273.ts.net:4318/v1/logs"
			method: post
			encoding:
				codec: json
			framing:
				method: newline_delimited
			headers:
				content-type: application/json

  # Optional: Authentication and other settings
  # insecure = true
  # headers = { "Key" = "Value" }
  # compression = "gzip"

  inputs = ["docker_logs"]
