x-common-env: &common-env
  OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
  VERSION_HASH: ${VERSION_HASH}
  DOMAIN: ${DOMAIN}
  NEXT_PUBLIC_KESSLER_API_URL: ${NEXT_PUBLIC_KESSLER_API_URL}
  INTERNAL_KESSLER_API_URL: ${INTERNAL_KESSLER_API_URL}
  INTERNAL_REDIS_ADDRESS: ${INTERNAL_REDIS_ADDRESS}

services:
  ingest:
    build:
      dockerfile: dev.ingest.Dockerfile
    command: go run /app/cmd/ingest/main.go
    develop:
      watch:
        - action: restart 
          path: ./cmd/ingest
          target: .
        - action: restart
          path: ./internal
          target: /app/internal
    env_file:
      - ../config/global.env
    environment:
      <<: *common-env
    volumes:
      - ./backend:/app
    working_dir: /app
    expose:
      - 4042
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.ingest.rule=PathPrefix(`/ingest_v1`)"

  backend:
    build:
      dockerfile: dev.server.Dockerfile
    command: go run /app/cmd/server/main.go
    develop:
      watch:
        - action: sync+restart 
          path: ./cmd/server/
          target: /app/cmd/server/
        - action: sync+restart 
          path: ./internal/
          target: /app/internal/
    environment:
      <<: *common-env
    env_file:
      - ../config/global.env
    expose:
      - 4041
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.go-backend.rule=PathPrefix(`/v2`)"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/v2"
