[build]
cmd = "go run cmd/ingest/main.go"
bin = "app"
full_bin = "./tmp/full_app"
# Define the necessary extensions and directories
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor"]

[log]
level = "debug"
color = "true"

[misc]
clean_on_update = true
