config:
  domain: "localhost"
  apiUrl: "http://localhost"

frontend:
  image:
    repository: fractalhuman1/kessler-frontend
    tag: latest
  replicas: 1
  domain: k8s-kessler.kessler.xyz
  port: 3000

backend:
  image:
    repository: fractalhuman1/kessler-backend-go
    tag: latest
  replicas: 1
  domain: k8s-kessler-api.kessler.xyz
  port: 4041
