// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: testing.sql

package dbstore

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT
    1 AS health_check
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var health_check int32
	err := row.Scan(&health_check)
	return health_check, err
}
