apiVersion: apps/v1
kind: Deployment
metadata:
  name: kessler-backend
  namespace: kessler
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        command:
        - ./kessler-backend-go
        envFrom:
        - configMapRef:
            name: kessler-public-config
        - secretRef:
            name: kessler-private-config
        livenessProbe:
          httpGet:
            path: /v2/search
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
