apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kessler-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  labels:
    app: kessler
  namespace: default
spec:
  rules:
  - host: {{ .Values.frontend.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kessler-frontend
            port:
              number: {{ .Values.frontend.port }}
  - host: {{ .Values.backend.domain }}
    http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: kessler-backend
            port:
              number: {{ .Values.backend.port }}
  {{/* tls: */}}
  {{/* - hosts: */}}
  {{/*   - {{ .Values.frontend.domain }} */}}
  {{/*   - {{ .Values.backend.domain }} */}}
  {{/*   secretName: kessler-tls-cert */}}
