spin_manifest_version = 2

[application]
name = "backend-spin"
version = "0.1.0"
authors = ["Nicole Venner <nvenner@protonmail.ch>"]
description = "Backend for Kessler"

[[trigger.http]]
route = "/"
component = "backend-spin"

[component.backend-spin]
source = "target/wasm32-wasip1/release/backend_spin.wasm"
allowed_outbound_hosts = []
[component.backend-spin.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
